dependencies:
- name: aio-csv-importer
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.16
- name: crucerisimo-landing
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.20
- name: dative-web
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.16
- alias: expose
  name: exposecontroller
  repository: http://chartmuseum.jenkins-x.io
  version: 2.3.89
- alias: cleanup
  name: exposecontroller
  repository: http://chartmuseum.jenkins-x.io
  version: 2.3.89
- name: nike
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.45
